/* eslint-disable @next/next/no-html-link-for-pages, react-hooks/set-state-in-effect */
"use client";

import { FormEvent, useEffect, useState } from "react";

type IconName = "stock" | "sales" | "accounting" | "multi" | "mobile" | "api" | "report" | "users";
type Module = { title: string; desc: string; icon: IconName; group: string };

const modules: Module[] = [
  { title: "Gestion des stocks", desc: "Suivez les quantités, les coûts et la disponibilité en temps réel.", icon: "stock", group: "Stocks" },
  { title: "Articles et catégories", desc: "Structurez votre catalogue, unités, groupes et tarifs.", icon: "stock", group: "Stocks" },
  { title: "Entrées et sorties", desc: "Tracez chaque mouvement, transfert et ajustement de stock.", icon: "stock", group: "Stocks" },
  { title: "Inventaires", desc: "Comparez le stock théorique au physique et validez les écarts.", icon: "report", group: "Stocks" },
  { title: "Ventes et commandes", desc: "Gérez le cycle client, de la commande à la facturation.", icon: "sales", group: "Ventes" },
  { title: "Paiements clients", desc: "Suivez les règlements, soldes et échéances par client.", icon: "sales", group: "Ventes" },
  { title: "Livraisons et tournées", desc: "Planifiez les tournées et contrôlez les quantités livrées.", icon: "sales", group: "Ventes" },
  { title: "Achats et fournisseurs", desc: "Pilotez commandes, réceptions et comptes fournisseurs.", icon: "stock", group: "Achats" },
  { title: "Comptabilité", desc: "Automatisez les écritures et disposez d'états financiers fiables.", icon: "accounting", group: "Finance" },
  { title: "Trésorerie", desc: "Centralisez caisses, banques, encaissements et décaissements.", icon: "accounting", group: "Finance" },
  { title: "Rapports et tableaux de bord", desc: "Transformez vos données en décisions avec des indicateurs clairs.", icon: "report", group: "Pilotage" },
  { title: "Gestion multisite", desc: "Supervisez plusieurs magasins, dépôts et filiales depuis un espace unique.", icon: "multi", group: "Pilotage" },
  { title: "Utilisateurs et permissions", desc: "Attribuez précisément les rôles et sécurisez les opérations sensibles.", icon: "users", group: "Administration" },
  { title: "Bomoi Sales Mobile", desc: "Vendez et consultez l'essentiel depuis Android et iOS.", icon: "mobile", group: "Mobilité" },
  { title: "API et intégrations", desc: "Connectez Bomoi à vos services grâce à une API documentée.", icon: "api", group: "Écosystème" },
];

const nav = [
  ["Produit", "/a-propos"], ["Modules", "/modules"], ["Secteurs", "/secteurs"], ["Avantages", "/avantages"], ["Ressources", "/documentation"],
];

function Icon({ name }: { name: IconName }) {
  const chars: Record<IconName, string> = { stock: "◇", sales: "↗", accounting: "₣", multi: "▦", mobile: "▯", api: "⌘", report: "⌁", users: "◎" };
  return <span className={`icon icon-${name}`} aria-hidden="true">{chars[name]}</span>;
}

function Header({ theme, setTheme }: { theme: string; setTheme: (v: string) => void }) {
  const [open, setOpen] = useState(false);
  return <header className="header"><div className="nav-wrap">
    <a className="brand" href="/" aria-label="Bomoi, accueil"><span className="brand-mark">B</span><span>Bomoi</span></a>
    <nav className={open ? "main-nav open" : "main-nav"} aria-label="Navigation principale">
      {nav.map(([label, href]) => <a key={href} href={href}>{label}</a>)}
      <a className="mobile-only" href="/actualites">Actualités</a><a className="mobile-only" href="/contact">Contact</a>
    </nav>
    <div className="nav-actions">
      <button className="theme-toggle" onClick={() => setTheme(theme === "dark" ? "light" : "dark")} aria-label={`Activer le mode ${theme === "dark" ? "clair" : "sombre"}`}><span>{theme === "dark" ? "☀" : "☾"}</span></button>
      <a className="btn btn-small" href="/demonstration">Démonstration</a>
      <button className="menu-toggle" onClick={() => setOpen(!open)} aria-label="Ouvrir le menu">{open ? "×" : "☰"}</button>
    </div>
  </div></header>;
}

function Footer() {
  return <footer><div className="footer-grid">
    <div><a className="brand" href="/"><span className="brand-mark">B</span><span>Bomoi</span></a><p>L’ERP moderne qui relie vos équipes, vos sites et vos opérations.</p><span className="placeholder-pill">Coordonnées officielles à compléter</span></div>
    <div><h4>Produit</h4><a href="/modules">Modules</a><a href="/secteurs">Secteurs</a><a href="/avantages">Avantages</a><a href="/demonstration">Démonstration</a></div>
    <div><h4>Ressources</h4><a href="/documentation">Documentation</a><a href="/actualites">Actualités</a><a href="/notes-de-version">Notes de version</a><a href="/faq">Questions fréquentes</a></div>
    <div><h4>Bomoi</h4><a href="/a-propos">À propos</a><a href="/partenaires">Partenaires</a><a href="/contact">Contact</a><a href="/confidentialite">Confidentialité</a></div>
  </div><div className="footer-bottom"><span>© 2026 Bomoi. Tous droits réservés.</span><span>Conçu pour les entreprises qui avancent.</span></div></footer>;
}

function Dashboard() {
  return <div className="dashboard-wrap" aria-label="Aperçu du tableau de bord Bomoi"><div className="glow" />
    <div className="dashboard">
      <div className="dash-side"><span className="mini-logo">B</span>{["Tableau de bord", "Ventes", "Achats", "Stocks", "Finances", "Rapports"].map((x,i)=><span className={i===0?"active":""} key={x}>{i===0?"▦":"○"} {x}</span>)}</div>
      <div className="dash-main"><div className="dash-head"><strong>Tableau de bord</strong><span>Tous les sites⌄</span></div>
        <div className="kpi-grid"><div className="kpi"><small>Chiffre d’affaires</small><b>124,8 M FC</b><em>↗ 18,6 %</em><div className="spark">⌁⌁╱⌁╱</div></div><div className="kpi"><small>Stock disponible</small><b>68%</b><div className="donut" /></div><div className="kpi"><small>Commandes</small><b>1 243</b><em>↗ 12,4 %</em><div className="bars"><i/><i/><i/><i/><i/></div></div><div className="kpi"><small>Trésorerie</small><b>38,6 M FC</b><em>↗ 15,8 %</em><div className="spark violet">⌁╱⌁⌁╱</div></div></div>
        <div className="chart"><span>Évolution du chiffre d’affaires</span><div className="chart-lines"><i/><i/><i/><i/><i/><i/><i/><i/></div><div className="chart-labels"><small>Jan.</small><small>Fév.</small><small>Mars</small><small>Avr.</small><small>Mai</small></div></div>
      </div>
    </div>
  </div>;
}

const benefits = [
  ["Une seule source de vérité", "Stocks, ventes, finances et opérations sont synchronisés dans un même environnement."],
  ["Conçu pour le multisite", "Gardez une vue consolidée tout en respectant l’autonomie de chaque site."],
  ["Décisions plus rapides", "Analysez vos indicateurs sans attendre la compilation manuelle de plusieurs fichiers."],
  ["Contrôle et traçabilité", "Suivez les actions, les validations et les mouvements sensibles de bout en bout."],
  ["Adapté à votre croissance", "Ajoutez progressivement des utilisateurs, sites et modules selon vos besoins."],
  ["Accessible partout", "Travaillez depuis le web ou Bomoi Sales Mobile, selon le rôle de chaque équipe."],
];

const sectors = ["Commerces & supermarchés", "Distribution", "Pharmacies", "Dépôts & entrepôts", "Entreprises multisites", "Organisations & projets"];

function HomePage() {
  return <>
    <section className="hero"><div className="hero-grid"><div className="hero-copy"><span className="eyebrow">ERP MODERNE · MULTISITE</span><h1>Pilotez toute votre entreprise, <span>simplement.</span></h1><p>Bomoi centralise vos stocks, ventes, achats, finances et opérations multisites dans une plateforme claire, rapide et sécurisée.</p><div className="hero-actions"><a className="btn" href="/demonstration">Demander une démonstration</a><a className="btn secondary" href="/modules">Découvrir les modules</a></div><div className="trust-row"><span>◉ <b>Sécurisé</b></span><span>ϟ <b>Rapide</b></span><span>▦ <b>Multisite</b></span><span>☁ <b>Accessible</b></span></div></div><Dashboard /></div></section>
    <section className="logos-strip"><span>ILS NOUS FONT CONFIANCE</span><div>{["PARTENAIRE 01", "RÉFÉRENCE 02", "PARTENAIRE 03", "RÉFÉRENCE 04"].map(x=><b key={x}>{x}</b>)}</div><small>Emplacements réservés aux logos officiels</small></section>
    <section className="section"><div className="section-heading"><div><span className="eyebrow">UN ERP COMPLET</span><h2>Tout ce qu’il faut pour mieux gérer.</h2></div><p>Des modules reliés entre eux pour suivre l’activité sans multiplier les outils ni ressaisir les mêmes données.</p></div><div className="feature-grid">{modules.slice(0,6).map(m=><a className="feature-card" href="/modules" key={m.title}><Icon name={m.icon}/><h3>{m.title}</h3><p>{m.desc}</p><span>Explorer <b>→</b></span></a>)}</div><div className="center"><a className="text-link" href="/modules">Voir les 15 modules →</a></div></section>
    <section className="section split-section"><div><span className="eyebrow">UNE VUE À 360°</span><h2>Vos chiffres deviennent des décisions.</h2><p>Bomoi relie les données de chaque service. Vous disposez d’une vision fiable des ventes, du stock, des créances et de la trésorerie, au moment où vous en avez besoin.</p><ul className="check-list"><li>Indicateurs actualisés en temps réel</li><li>Rapports détaillés par site, article ou période</li><li>Contrôle des accès selon les responsabilités</li></ul><a className="btn secondary" href="/avantages">Pourquoi choisir Bomoi</a></div><div className="report-card"><div className="report-top"><span>Performance globale</span><b>Ce mois-ci⌄</b></div><strong>+24,8%</strong><small>Progression du chiffre d’affaires</small><div className="big-bars">{[45,62,50,74,68,88,82,100].map((h,i)=><i key={i} style={{height:`${h}%`}} />)}</div><div className="report-stats"><span><b>98,7%</b>Taux de service</span><span><b>12</b>Sites actifs</span><span><b>28 542</b>Références</span></div></div></section>
    <section className="section"><div className="section-heading"><div><span className="eyebrow">POUR VOTRE SECTEUR</span><h2>Bomoi s’adapte à votre réalité.</h2></div><p>Une base commune, configurée selon vos flux, vos équipes et votre organisation.</p></div><div className="sector-grid">{sectors.map((s,i)=><a href="/secteurs" key={s}><span>0{i+1}</span><h3>{s}</h3><b>→</b></a>)}</div></section>
    <section className="section benefits-section"><div className="section-heading"><div><span className="eyebrow">LES AVANTAGES BOMOI</span><h2>Moins de friction. Plus de maîtrise.</h2></div></div><div className="benefit-grid">{benefits.slice(0,4).map(([t,d],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
    <NewsPreview />
    <CTA />
  </>;
}

function PageHero({ eyebrow, title, intro }: { eyebrow: string; title: string; intro: string }) { return <section className="page-hero"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{intro}</p></section>; }
function CTA() { return <section className="cta"><div><span className="eyebrow">PRÊT À AVANCER ?</span><h2>Voyez Bomoi à l’œuvre.</h2><p>Parlez-nous de votre activité. Notre équipe vous présentera les modules les plus adaptés à vos besoins.</p></div><div><a className="btn light" href="/demonstration">Demander une démonstration</a><a className="btn ghost" href="/contact">Contacter l’équipe</a></div></section>; }

function AboutPage() { return <><PageHero eyebrow="À PROPOS" title="Une gestion plus claire pour des entreprises plus fortes." intro="Bomoi est une plateforme ERP conçue pour aider les organisations à structurer leurs opérations, fiabiliser leurs données et grandir avec maîtrise."/><section className="section prose-grid"><div><h2>Notre raison d’être</h2><p>De nombreuses entreprises pilotent encore leurs activités avec des informations dispersées. Bomoi rassemble ces flux dans un environnement cohérent, adapté aux réalités des équipes et des organisations multisites.</p><p>Notre ambition est simple : rendre les outils de gestion avancés plus accessibles, plus lisibles et réellement utiles au quotidien.</p></div><div className="quote-card"><span>NOTRE VISION</span><blockquote>Faire de la donnée opérationnelle un levier de confiance, de performance et de croissance durable.</blockquote><small>Texte institutionnel provisoire — à valider</small></div></section><section className="section values"><h2>Ce qui guide Bomoi</h2><div className="feature-grid three">{[["Clarté","Une information compréhensible et exploitable."],["Fiabilité","Des données tracées, cohérentes et sécurisées."],["Proximité","Une solution pensée avec les réalités du terrain."]].map(([t,d])=><article className="feature-card" key={t}><h3>{t}</h3><p>{d}</p></article>)}</div></section><CTA/></>; }

function ModulesPage() { const groups=[...new Set(modules.map(m=>m.group))]; return <><PageHero eyebrow="15 MODULES CONNECTÉS" title="Une plateforme. Toute votre activité." intro="Activez les fonctions dont votre entreprise a besoin aujourd’hui et faites évoluer Bomoi avec votre organisation."/><section className="section module-catalog">{groups.map(g=><div className="module-group" key={g}><div><span>{g}</span><small>{modules.filter(m=>m.group===g).length} module(s)</small></div><div>{modules.filter(m=>m.group===g).map(m=><article key={m.title}><Icon name={m.icon}/><div><h3>{m.title}</h3><p>{m.desc}</p></div></article>)}</div></div>)}</section><CTA/></>; }

function SectorsPage() { const desc=["Centralisez ventes, stocks, caisses et points de vente.","Coordonnez commandes, approvisionnement et livraisons.","Suivez lots, péremptions, articles et mouvements sensibles.","Maîtrisez emplacements, quantités et traçabilité.","Comparez les performances et consolidez les données.","Gérez budgets, actifs, équipes et reporting opérationnel."]; return <><PageHero eyebrow="SECTEURS D’ACTIVITÉ" title="Une solution qui comprend vos opérations." intro="Bomoi s’adapte aux processus de chaque secteur sans perdre la cohérence d’une plateforme intégrée."/><section className="section sector-detail">{sectors.map((s,i)=><article key={s}><span>0{i+1}</span><div><h2>{s}</h2><p>{desc[i]}</p><ul><li>Configuration adaptée</li><li>Rapports par activité</li><li>Accès par responsabilité</li></ul></div></article>)}</section><CTA/></>; }

function AdvantagesPage() { return <><PageHero eyebrow="AVANTAGES" title="Travaillez avec des données fiables, partout." intro="Bomoi réduit les tâches répétitives, fluidifie la collaboration et donne aux responsables une vision consolidée de l’activité."/><section className="section"><div className="benefit-grid large">{benefits.map(([t,d],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section><section className="section comparison"><div><span className="eyebrow">AVANT BOMOI</span><h2>Fichiers dispersés, ressaisies et décisions tardives.</h2></div><div><span className="eyebrow">AVEC BOMOI</span><h2>Une information partagée, tracée et disponible.</h2></div></section><CTA/></>; }

const news = [
  {date:"30 juillet 2026", tag:"Produit", title:"Nouveau : configuration sécurisée des webhooks", text:"Les entreprises peuvent désormais configurer leurs callbacks et signatures HMAC."},
  {date:"24 juillet 2026", tag:"Mobile", title:"Bomoi Sales Mobile entre en phase de préparation", text:"Une expérience de vente dédiée aux équipes Android et iOS."},
  {date:"18 juillet 2026", tag:"Stocks", title:"Des inventaires multisites plus précis", text:"Nouveaux filtres, validation multiple et rapports enrichis."},
];
function NewsPreview() { return <section className="section news-section"><div className="section-heading"><div><span className="eyebrow">ACTUALITÉS</span><h2>Les dernières évolutions.</h2></div><a className="text-link" href="/actualites">Toutes les actualités →</a></div><div className="news-grid">{news.map(n=><article key={n.title}><div className="news-image"><span>Visuel à fournir</span></div><small>{n.tag} · {n.date}</small><h3>{n.title}</h3><p>{n.text}</p><a href="/actualites">Lire l’article →</a></article>)}</div></section>; }
function NewsPage() { return <><PageHero eyebrow="ACTUALITÉS" title="La vie et les évolutions de Bomoi." intro="Retrouvez les nouveautés produit, conseils pratiques et informations de l’écosystème Bomoi."/><section className="section news-grid all">{[...news,...news.map((n,i)=>({...n,title:["Mieux piloter ses tournées de livraison","Comprendre le stock disponible","Les tableaux de bord au service des décisions"][i],tag:"Conseils"}))].map((n,i)=><article key={i}><div className="news-image"><span>Visuel éditorial {i+1}</span></div><small>{n.tag} · {n.date}</small><h3>{n.title}</h3><p>{n.text}</p><a href="#">Lire l’article →</a></article>)}</section></>; }

function ReleasesPage() { const releases=[{v:"2.10.113",d:"30 juillet 2026",items:["Configuration des webhooks par entreprise","Signature HMAC des callbacks","Améliorations de fiabilité des opérations"]},{v:"2.10.112",d:"27 juillet 2026",items:["Inventaires multisites et validation multiple","Rapports PDF et Excel enrichis","Optimisation des mouvements de stock"]},{v:"2.10.111",d:"18 juillet 2026",items:["Nouveaux rapports commandes et livraisons","Améliorations du thème sombre","Corrections de performance"]}]; return <><PageHero eyebrow="NOTES DE VERSION" title="Bomoi évolue, version après version." intro="Consultez les nouveautés, améliorations et corrections livrées dans chaque version."/><section className="section releases">{releases.map((r,i)=><article key={r.v}><div><span className="version">v{r.v}</span><time>{r.d}</time>{i===0&&<b>Version actuelle</b>}</div><ul>{r.items.map(x=><li key={x}>{x}</li>)}</ul></article>)}</section></>; }

function PartnersPage() { return <><PageHero eyebrow="PARTENAIRES & RÉFÉRENCES" title="Un écosystème fondé sur la confiance." intro="Bomoi grandit avec ses clients, partenaires d’implémentation et acteurs technologiques."/><section className="section partner-grid">{["Partenaire technologique","Client de référence","Partenaire intégrateur","Client multisite","Partenaire métier","Organisation partenaire"].map((x,i)=><article key={i}><div>LOGO</div><h3>{x} {String(i+1).padStart(2,"0")}</h3><p>Présentation officielle à compléter après validation du partenaire.</p></article>)}</section><section className="section partner-note"><h2>Devenir partenaire Bomoi</h2><p>Vous accompagnez des entreprises dans leur transformation, leur gestion ou leur infrastructure ? Construisons ensemble des solutions adaptées.</p><a className="btn" href="/contact">Parler à l’équipe</a></section></>; }

const docCats=[{title:"Bien démarrer",items:["Présentation de Bomoi","Se connecter","Configurer votre entreprise","Comprendre la navigation"]},{title:"Stocks",items:["Créer un article","Enregistrer une entrée","Effectuer une sortie","Réaliser un inventaire"]},{title:"Ventes",items:["Créer une commande","Enregistrer un paiement","Planifier une livraison"]},{title:"Administration",items:["Gérer les utilisateurs","Rôles et permissions","Configuration multisite"]}];
function DocumentationPage() { const [query,setQuery]=useState(""); const filtered=docCats.map(c=>({...c,items:c.items.filter(i=>i.toLowerCase().includes(query.toLowerCase()))})); return <div className="docs-layout"><aside className="docs-sidebar"><a className="docs-home" href="/documentation">Centre de documentation</a><label className="doc-search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher un guide..." /></label>{filtered.map(c=><div className="doc-category" key={c.title}><h4>{c.title}</h4>{c.items.map((i,n)=><a className={c.title==="Stocks"&&n===1?"selected":""} key={i} href="#article">{i}</a>)}</div>)}</aside><main className="doc-main" id="article"><div className="breadcrumbs"><a href="/documentation">Documentation</a><span>›</span><a href="#">Stocks</a><span>›</span><b>Enregistrer une entrée</b></div><div className="doc-content"><article><div className="doc-title"><span className="version">Bomoi 2.10+</span><h1>Enregistrer une entrée de stock</h1><p>Apprenez à enregistrer la réception ou l’ajout d’articles dans un stockage.</p><small>Mis à jour le 30 juillet 2026 · 6 min de lecture</small></div><div className="callout info"><b>Information</b><p>Vous devez disposer de la permission de création des mouvements de stock.</p></div><h2 id="before">Avant de commencer</h2><p>Vérifiez que l’article, le stockage et le type de mouvement existent dans votre espace Bomoi.</p><h2 id="steps">Étapes</h2><ol><li>Dans le menu principal, ouvrez <b>Stocks</b>, puis <b>Mouvements</b>.</li><li>Sélectionnez <b>Nouvelle entrée</b>.</li><li>Renseignez le stockage, le type, l’article, l’emplacement et la quantité.</li></ol><div className="screenshot-placeholder"><span>CAPTURE D’ÉCRAN À INSÉRER</span><small>Écran : création d’une entrée de stock</small></div><div className="callout tip"><b>Conseil</b><p>Ajoutez plusieurs articles à la même opération pour accélérer la saisie d’une réception.</p></div><h2 id="validate">Valider l’opération</h2><p>Contrôlez les lignes avant confirmation. Selon la configuration, une validation supplémentaire peut être requise.</p><div className="callout warning"><b>Attention</b><p>Une opération confirmée modifie immédiatement le stock disponible.</p></div><div className="callout error"><b>Erreur fréquente</b><p>Si l’enregistrement échoue, vérifiez que le type de mouvement sélectionné accepte les entrées.</p></div><div className="doc-nav"><a href="#">← Créer un article</a><a href="#">Effectuer une sortie →</a></div></article><aside className="toc"><b>Dans cet article</b><a href="#before">Avant de commencer</a><a href="#steps">Étapes</a><a href="#validate">Valider l’opération</a><hr/><span>Cette page vous a-t-elle aidé ?</span><div><button>Oui</button><button>Non</button></div></aside></div></main></div>; }

function FormPage({type}:{type:"demo"|"contact"}) { const [sent,setSent]=useState(false); function submit(e:FormEvent){e.preventDefault();setSent(true)} const demo=type==="demo"; return <><PageHero eyebrow={demo?"DÉMONSTRATION":"CONTACT"} title={demo?"Découvrez Bomoi avec vos propres enjeux.":"Parlons de votre projet."} intro={demo?"Présentez-nous votre activité et recevez une démonstration adaptée à vos flux.":"Une question sur Bomoi, ses modules ou son déploiement ? Notre équipe vous répond."}/><section className="section form-layout"><div><h2>{demo?"Une présentation personnalisée":"Nous sommes à votre écoute"}</h2><p>{demo?"Pendant la démonstration, nous parcourrons les modules correspondant à votre secteur, vos sites et vos priorités.":"Utilisez ce formulaire en attendant la validation des coordonnées officielles de Bomoi."}</p><ul className="check-list"><li>Échange sur vos processus actuels</li><li>Présentation des modules pertinents</li><li>Réponses à vos questions techniques</li></ul><div className="contact-card"><small>CONTACT DIRECT</small><b>Coordonnées à compléter</b><span>Kinshasa, République démocratique du Congo</span></div></div>{sent?<div className="success"><span>✓</span><h2>Demande enregistrée</h2><p>Merci. Dans la version finale, cette demande sera transmise à l’équipe Bomoi.</p><button className="btn" onClick={()=>setSent(false)}>Nouvelle demande</button></div>:<form onSubmit={submit}><div className="form-row"><label>Prénom et nom<input required placeholder="Votre nom"/></label><label>Entreprise<input required placeholder="Nom de l’entreprise"/></label></div><div className="form-row"><label>Adresse e-mail<input required type="email" placeholder="vous@entreprise.com"/></label><label>Téléphone<input placeholder="+243 ..."/></label></div>{demo&&<div className="form-row"><label>Secteur<select defaultValue=""><option value="" disabled>Sélectionner</option>{sectors.map(s=><option key={s}>{s}</option>)}</select></label><label>Nombre de sites<select><option>1 site</option><option>2 à 5 sites</option><option>6 à 20 sites</option><option>Plus de 20 sites</option></select></label></div>}<label>Votre message<textarea required rows={5} placeholder={demo?"Décrivez brièvement votre activité et vos besoins...":"Comment pouvons-nous vous aider ?"}/></label><button className="btn" type="submit">{demo?"Envoyer ma demande":"Envoyer le message"}</button><small className="form-note">Formulaire de démonstration — connexion au service d’envoi à prévoir.</small></form>}</section></>; }

function FAQPage() { const qs=[["À quelles entreprises Bomoi s’adresse-t-il ?","Aux commerces, distributeurs, pharmacies, dépôts, entrepôts et organisations qui souhaitent centraliser leur gestion, y compris avec plusieurs sites."],["Peut-on utiliser seulement certains modules ?","Oui. La configuration peut être adaptée aux besoins actuels de l’entreprise et évoluer progressivement."],["Bomoi fonctionne-t-il sur mobile ?","L’interface web est responsive et l’application Bomoi Sales Mobile est prévue pour les équipes commerciales Android et iOS."],["Les droits des utilisateurs sont-ils configurables ?","Oui. Les rôles et permissions permettent de contrôler l’accès aux fonctions et opérations sensibles."],["Bomoi propose-t-il une API ?","Oui. Des API et mécanismes d’intégration permettent de relier Bomoi à d’autres services."],["Comment obtenir une démonstration ?","Remplissez le formulaire de démonstration. L’équipe Bomoi vous contactera pour comprendre votre contexte."]]; return <><PageHero eyebrow="QUESTIONS FRÉQUENTES" title="Les réponses à vos premières questions." intro="Tout ce qu’il faut savoir avant de découvrir Bomoi plus en détail."/><section className="section faq">{qs.map(([q,a],i)=><details key={q} open={i===0}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</section><CTA/></>; }

function PrivacyPage() { return <><PageHero eyebrow="CONFIDENTIALITÉ" title="Politique de confidentialité." intro="Cette page décrit provisoirement les principes de traitement des données du site public Bomoi."/><section className="section legal"><div className="callout warning"><b>Document provisoire</b><p>Le contenu devra être validé juridiquement avant la publication publique du site.</p></div><h2>1. Données collectées</h2><p>Le site pourra collecter les informations fournies volontairement dans les formulaires de contact et de démonstration : identité, coordonnées professionnelles, entreprise et message.</p><h2>2. Finalités</h2><p>Ces données seront utilisées pour répondre aux demandes, organiser des démonstrations, améliorer les services et assurer le suivi de la relation commerciale.</p><h2>3. Conservation et sécurité</h2><p>Les données seront conservées pendant une durée proportionnée à la finalité et protégées par des mesures organisationnelles et techniques adaptées.</p><h2>4. Vos droits</h2><p>Les modalités d’accès, de rectification ou de suppression seront précisées avec les coordonnées officielles du responsable du traitement.</p><h2>5. Contact</h2><p>Adresse de contact relative à la confidentialité : <b>à compléter avant publication</b>.</p><small>Dernière mise à jour provisoire : 1er août 2026.</small></section></>; }

function AppContent({route}:{route:string}) { switch(route){case"/":return <HomePage/>;case"/a-propos":return <AboutPage/>;case"/modules":return <ModulesPage/>;case"/secteurs":return <SectorsPage/>;case"/avantages":return <AdvantagesPage/>;case"/actualites":return <NewsPage/>;case"/documentation":return <DocumentationPage/>;case"/notes-de-version":return <ReleasesPage/>;case"/partenaires":return <PartnersPage/>;case"/demonstration":return <FormPage type="demo"/>;case"/contact":return <FormPage type="contact"/>;case"/faq":return <FAQPage/>;case"/confidentialite":return <PrivacyPage/>;default:return <><PageHero eyebrow="404" title="Cette page reste à écrire." intro="Revenez à l’accueil ou consultez la documentation Bomoi."/><div className="center section"><a className="btn" href="/">Retour à l’accueil</a></div></>}}

export default function BomoiSite({route}:{route:string}) {
  const [theme,setThemeState]=useState("dark");
  // Synchronize the saved browser preference after hydration.
  useEffect(()=>{const saved=localStorage.getItem("bomoi-theme"); const next=saved||((matchMedia("(prefers-color-scheme: light)").matches)?"light":"dark");setThemeState(next);document.documentElement.dataset.theme=next},[]);
  const setTheme=(next:string)=>{setThemeState(next);document.documentElement.dataset.theme=next;localStorage.setItem("bomoi-theme",next)};
  const docs=route==="/documentation";
  return <div className="site"><Header theme={theme} setTheme={setTheme}/><AppContent route={route}/>{!docs&&<Footer/>}</div>;
}
